version: '3'
services:
  springbootdockerdemo:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    image: springbootdockerdemo_image:1.0.1
    container_name: springbootdockerdemo_container
    ports:
    - 8080:8080
    entrypoint:
      TZ: Asia/Shanghai